### ISSUE TITLE
Soil parameter for grid cells having snow

### ISSUE THREAD

**Issue by LSRathore** [jschap1/VICMATLAB#1]
I am facing a problem regarding the preparation of soil parameter file for VIC 4.2.
Some grids of my region are in glacier area and do not have soil properties. HWSD dataset shows no texture for glacier and water. 
In that case, what properties should I assign to that grid cells?

**Comment by jschap1** [comment]
The thing about VIC is it doesn't have a glacier model. Various researchers have incorporated glacier models (of varying degrees of complexity) into their VIC-modeling framework. For example, Quidong Zhao et al. have coupled a degree-day melt model to VIC (2015, J. of Hydrometeorology) and also a physically-based glacier melt model (2013, Environmental Earth Sciences). The work of Bibi Naz (e.g. her 2009 dissertation "The hydrologic sensitivity of the upper Indus River to glacier changes in the western Karakoram Himalayas") is also relevant.

One way or another, I would expect that soil properties are less important for glacier-covered cells than the fact that they are glacier-covered. One idea (which is explored in the literature cited above) is to replace VIC-generated runoff for glacier cells with runoff generated from a glacier-melt model. Sorry that I don't have a straight answer, but check out those papers, and keep me posted if you think of a good way to incorporate glaciers!

**Comment by LSRathore** [comment]
VIC 4.2 has a glacier model, and it comes with additional functionalities for glaciers. I tried to simulate over the region but it produced a soil file regarding error. I think it requires some more properties for glacier cells, but there is no sample soil file provided with that, and I couldnt run that.
Replacing the streamflow by another snow model could be alternate, I would try that.

**Comment by jschap1** [comment]
I was not aware of a VIC glacier model. Could you point me to some documentation describing this model? VIC 4.2 can simulate frozen soils, perhaps that is that what you are referring to?

**Comment by LSRathore** [comment]
You can check out the glacier model by clicking the link:  [https://github.com/UW-Hydro/VIC/tree/support/VIC.4.2.glacier](url) 
It does not have specific documents for the model and its similar to VIC4.2 more or less, but one or two fields must be added to soil parameter file. Let me know if you run this.

**Comment by jschap1** [comment]
Thanks for the link. I see that there was a VIC glacier model in development several years ago, but it doesn't look like it has ever been completed or used in any studies. Joe Hamman (the developer) wrote in the README for his VIC glacier repository that the repo is out of date, and interested people should contact him (https://github.com/jhamman/VIC_glacier).

**Comment by jschap1** [comment]
I wrote to Dr. Hamman. He is unable to provide support using the VIC glacier module, but he pointed me to a brief write-up about it in a 2019 journal paper: (https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018EF001047). 

I will not have time to work on glacier modeling for at least the next month or so, but if you would like to fork VICMATLAB and add scripts for setting up the VIC 4.2 glacier module, definitely feel free!

**Comment by LSRathore** [comment]
Thanks for the link, I will go through the paper. I have no knowledge of MATLAB otherwise I would have surely tried to add something in the repo. VICMATLAB is really good and I hope it helps the researchers.

**Comment by jschap1** [comment]
Sure, thanks. There is definitely more to do in terms of refining VICMATLAB, though. It's still pretty rough, at this point.
